[package]
authors = ['twicrates']
description = 'FRAME pallet define custom awoogable minting logic'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'awooga-pallet'
repository = 'https://github.com/twicrates/awooga-pallet/'
version = '0.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
awooga-pallet-commodities = { path = '../awooga-nft-pallet', default-features = false, version = '1.0.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'awooga-pallet-commodities/std',
    'sp-core/std',
    'sp-std/std',
    'sp-runtime/std',
    'sp-io/std',
]
